### ISSUE TITLE
How to use JMap  ?

### ISSUE THREAD

**Issue by raindy29** [SpinaNico/jsonable#1]
I don't know how to use JMap  type,
Please give me  example

{id:100,  items: { 'pc': {price: 500, title: 'a01'},'nb': {price: 100, title: 'b01'} }}

════════ Exception caught by gesture ═══════════════════════════════════════════════════════════════
The following JsonUnsupportedObjectError was thrown while handling a gesture:
Converting object to an encodable object failed: _LinkedHashMap len:1

`
    var p = Person(id:100,contact: {'pc':Contact(price:500,title:'a01') ,  'nb':Contact(price:100,title:'b01')} );
    print(p.toJson());

class Person with Jsonable {
   JNum id;
  JMap<String, Contact> contact;
  Person({id,contact}) {
    this.id = this.jNum("id", initialValue:id);
    this.contact = this.jMap<String, Contact>("contact", builder: () => Contact()
       , initialValue:contact);
  }
}

class Contact with Jsonable {
  JNum price;
  JString title;
  Contact({price,title}) {
    this.price = this.jNum("price", initialValue: price);
    this.titl = this.jString("title", initialValue: title);
  }
}
`

**Comment by ocinsh** [comment]
Hi, the JMAP is only for the Map type, it is an unusual type that I have inserted to allow you to pass also the simple value "Map". 

You can use Jmap with Jclass, but not yet with Jsonable it will be supported in future releases.
I corrected your code, using JClass but you cannot pass that initial value

```dart
class Person with Jsonable {
  JNum id;
  JMap<String, JClass<Contact>> contact;
  Person({id, contact}) {
    this.id = this.jNum("id", initialValue: id);
    this.contact = this.jMap<String, JClass<Contact>>(
      "contact",
      builder: () => Contact(),
    );
  }
}

class Contact with Jsonable {
  JNum price;
  JString title;
  Contact({price, title}) {
    this.price = this.jNum("price", initialValue: price);
    this.title = this.jString("title", initialValue: title);
  }
}

```
a tip that I give you, and not to use "initialValue" for complex values like a class (Jsoanble), I have yet to structure the tests for this part of the library.

When you find yourself having to pass values to fill your `Jsonable`, I recommend this medology

```dart
main() {
  var p = Person()
    ..fromMap({
      "id": 100,
      "contact": {
        'pc': {"price": 500, "title": 'a01'},
        'nb': {"price": 100, "title": 'b01'}
      }
    });
  print(p.toJson());

  var s =
      """{"id":100,"contact":{"pc":{"price":500,"title":"a01"},"nb":{"price":100,"title":"b01"}}}""";

  p.fromJson(s);
  print(p.toJson());
}

```

I hope I have been exhaustive, if something is not clear you can tell me.

the library was created to avoid generated (ugly) code, and to avoid reflection.

**Comment by raindy29** [comment]
Your code can solve,thanks.
